name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - 'main'

env:
  GC_PROJECT_ID: 'netviser-454113'
  REGION: 'asia-southeast2'
  SERVICE_ACCOUNT_NAME: 'netviser-action'
  GAR_NAME: 'netviser-backend-gar-asia-southeast2'
  GAR_LOCATION: 'asia-southeast2'
  SERVICE: 'netviser-backend'
  GCS_BUCKET_NAME: 'netviser-gcs-asia-southeast1'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: 'actions/checkout@v4'

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: GAR Auth
        run: |
          gcloud auth configure-docker "${{ env.REGION }}-docker.pkg.dev"

      - name: Build and Push Container
        run: |
          DOCKER_TAG="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GC_PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.SERVICE }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE }} \
            --image "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.GC_PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.SERVICE }}:${{ github.sha }}" \
            --region ${{ env.REGION }} \
            --project ${{ env.GC_PROJECT_ID }} \
            --cpu 8 \
            --min-instances 1 \
            --max-instances 1 \
            --memory 16Gi \
            --platform managed \
            --service-account "${{ env.SERVICE_ACCOUNT_NAME }}@${{ env.GC_PROJECT_ID }}.iam.gserviceaccount.com" \
            --set-env-vars "GC_PROJECT_ID=${{ env.GC_PROJECT_ID }},GCS_BUCKET_NAME=${{ env.GCS_BUCKET_NAME }},GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }},GEMINI_MODEL=${{ secrets.GEMINI_MODEL }},REDIS_HOST=${{ secrets.REDIS_HOST }},REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }},REDIS_PORT=${{ secrets.REDIS_PORT }},REDIS_USERNAME=${{ secrets.REDIS_USERNAME }},ENV=${{ secrets.ENV }}"

      - name: Allow Unauthenticated Access
        run: |
          gcloud run services add-iam-policy-binding ${{ env.SERVICE }} \
            --region=${{ env.REGION }} \
            --project=${{ env.GC_PROJECT_ID }} \
            --member="allUsers" \
            --role="roles/run.invoker"
